### ISSUE TITLE
Hanging signs and Glowing signs

### ISSUE THREAD

**Issue by Sylnin** [tr7zw/Exordium#103]
Hanging signs have the text hanging off the sign, and signs with glowing text are blinding af
![2023-09-06_10 55 38](https://github.com/tr7zw/Exordium/assets/63519074/70e2ae41-49c8-478c-8c3b-691ae4e9d733)
![2023-09-06_10 55 42](https://github.com/tr7zw/Exordium/assets/63519074/05c0724c-d40c-4293-8068-bf75dc14bfd2)

**Comment by tr7zw** [comment]
Duplicate #101

**Comment by Sylnin** [comment]
figured out if i disable sign buffering, the text goes normal, but my frames drop from 50-60 to like 10

**Comment by tr7zw** [comment]
It's fixed in the next release(that's why this issue is a duplicate of a closed issue). The glowing is your shader, it has nothing to do with Exordium.
