### ISSUE TITLE
crosshair doesnt update with f5 or with going into spectator

### ISSUE THREAD

**Issue by dbrighthd** [tr7zw/Exordium#105]
![image](https://github.com/tr7zw/Exordium/assets/68525639/287e26e3-af5e-4cb5-a8ef-c08058dd1ef2)
![image](https://github.com/tr7zw/Exordium/assets/68525639/c4198a6a-1f4c-4a70-a1c6-dc0884f0c851)
 they update after a left click 
 happens even when force crosshair updates is on

**Comment by Pie-Not-Lie** [comment]
Was just encountering this same issue and switched around mods until I found out it was Exordium. To add more info to this bug:
The crosshair doesn't invert, disappear during F5 or spectator, can't be forced to update, does this even with "Fast Crosshair" set to OFF, and it doesn't seem to be a mod conflict of any kind.

**Comment by JustAlittleWolf** [comment]
For me the crosshair updates when punching, however it stays in the hidden mode when switching back to first person which is annoying. You have to punch again to see the crosshair again

**Comment by JustAlittleWolf** [comment]
Also the option for fast crosshair doesn't toggle the crosshair, I think its always enabled by default

**Comment by tr7zw** [comment]
Huh that's an odd one, since the crosshair should not be touched at all as long as the buffering is off. Will look into it.

**Comment by tr7zw** [comment]
> private BufferedComponent **crosshair**BufferedComponent = new BufferedComponent(true, () -> ExordiumModBase.instance.config.**debugScreenSettings**)

Ah damn, you're right. That copy-paste fail made it through.

**Comment by tr7zw** [comment]
Pushing out 1.2.1 to fix this as this affects anyone with the default settings.
