### ISSUE TITLE
[Forge 1.20.1] Crash on launch with DivineRPG

### ISSUE THREAD

**Issue by MrKashew** [tr7zw/Exordium#109]
Modpack successfully launches upon removal of Exordium, so a bit confident it is a compatibility issue as you described between Exordium and DivineRPG UI elements
[crash-2023-09-11_00.07.35-fml.txt](https://github.com/tr7zw/Exordium/files/12573194/crash-2023-09-11_00.07.35-fml.txt)

**Comment by tr7zw** [comment]
Closing all forge issues as the forge version never worked and theres no plans for a new one.
