### ISSUE TITLE
incompatibility with immediatelyfast 

### ISSUE THREAD

**Issue by whoiamwhy** [tr7zw/Exordium#118]
i have some bugs with gui using immediatelyfast 1.2.6 with exordium 1.2.1, without the mod exordium everything works fine

https://github.com/tr7zw/Exordium/assets/131746105/2a53024b-b38d-4459-af6e-fd36e4c3255e

![image](https://github.com/tr7zw/Exordium/assets/131746105/796afee9-6c1b-4288-b229-2e8b70d89fcb)

[debug.log](https://github.com/tr7zw/Exordium/files/13257404/debug.log)
[latest.log](https://github.com/tr7zw/Exordium/files/13257406/latest.log)

**Comment by tr7zw** [comment]
Didnt I pull the Forge release?

**Comment by whoiamwhy** [comment]
> Didnt I pull the Forge release?


Modrinth has it

**Comment by tr7zw** [comment]
Yea, Modrinth doesn't offer to archive it, so I just set it down to alpha so most launchers don't even show it. It's broken, don't use it, bestcase use Fabric since your modlist seems to fit that better anyway, with most of these mods being mainly Fabric mods.

**Comment by tr7zw** [comment]
Closing this as it's Forge, not going to try to re-release any version for Forge at this point.
