### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by DonorKrovi** [tr7zw/Exordium#119]
https://mcpaste.io/adcbf3de479e92a6

**Comment by DonorKrovi** [comment]
Open client = crash

**Comment by tr7zw** [comment]
It's not finding a file for some reason. Also, the Forge version got pulled and isn't supported anymore, as it's broken. Consider switching to Fabric.

**Comment by tr7zw** [comment]
Also from what I can see you are using an illegal pirated launcher, so double no support for that.
