### ISSUE TITLE
[Feature Request] 1.20.3/4 Compatibility

### ISSUE THREAD

**Issue by R00tB33rMan** [tr7zw/Exordium#123]
I assume you are aware but 1.20.3/4 released not too long ago and unfortunately Exordium crashes when connecting to any server/world but not on startup. I appreciate your dedication and efforts towards this project and am only attempting to make an issue report to have a present issue available for those whom may assume it's already compatible!

**Comment by R00tB33rMan** [comment]
No worries. Thank you for your response! I really appreciate your work!

**Comment by tr7zw** [comment]
Fixed by @rybot666 .
