### ISSUE TITLE
nothing renders when enabled in config (also pressing the config button in the mods screen crashes the game)

### ISSUE THREAD

**Issue by dxcvvxd** [tr7zw/Exordium#125]
so when i enable an optimization in the config (i have to modify the exordium.json file because when pressing the config button ingame it just crashes and it doesnt happen with any other mod)
the ui element of choice just doesnt render, i also have a heavily modified up to date modpack with almost every single optimization mod out there for the latest version.
i can attach crashing logs and the mod list if you want because i would really like to continue using this mod as it is a must nowadays

**Comment by tr7zw** [comment]
Sounds like you are running the 1.20.2 version on 1.20.4. That wont work.

**Comment by dxcvvxd** [comment]
@tr7zw im having the same issue again, on 1.20.4, it doesnt render anything thats enabled in the config
(this happened some time ago, maybe 2 months? when exordium got updated) and i want to reopen the issue

**Comment by tr7zw** [comment]
This issue is from 2023... Open a new one and with logs (especially when it crashes)
