### ISSUE TITLE
[1.19.4] Compatibility issue with Fabric Loader 0.15

### ISSUE THREAD

**Issue by Estecka** [tr7zw/Exordium#130]
Hi,

When using Fabric Loader 0.15, Exordium 1.1.2+1.19.4 depends on MixinExtra in a way that prevents other mods from using a more recent versions of it. (See https://github.com/FabricMC/fabric-loader/issues/885#issuecomment-1884899186 for details and repro) 

Quoting LlamaLad:
> That version of exordium shades MixinExtras without relocating it. This has never been supported and it should be reported to them.

**Comment by tr7zw** [comment]
Duplicate #129
