### ISSUE TITLE
[Incorrect] Ignore this issue

### ISSUE THREAD

**Issue by nsde** [tr7zw/Exordium#132]
# ! Exoridum is safe, I was mistaken!
![image](https://github.com/tr7zw/Exordium/assets/67185896/698b0846-6ad9-40d2-aa34-bbe7d82c1d49)

**Comment by tr7zw** [comment]
Thats multimc that kaspersky is picking up. I'd assume it's a false positive of Kaspersky or you downloaded some fake version. I'd ask on the multimc discord. Also which exordium file did you download so I can throw it into virustotal to check if something incorrectly picked it up.

**Comment by tr7zw** [comment]
Again: It's kaspersky picking up MultiMC. This has nothing to do with this mod. Also its not saying that MultiMC is malware, just that it has the characteristics.
