### ISSUE TITLE
Detail Armor Bar protection effect doesn't work

### ISSUE THREAD

**Issue by IntMarco** [tr7zw/Exordium#142]
https://mclo.gs/Bo7Lgvd
![2024-05-03_20 11 57](https://github.com/tr7zw/Exordium/assets/124934175/e5bfb1df-507d-4bf8-b879-a78d8d58c7c5)

**Comment by tr7zw** [comment]
If the mod adds any animation, then you need to turn off Exordium for that.

**Comment by IntMarco** [comment]
Understood, but you should remove it from the compatible mods in the description of yours on Modrinth

**Comment by tr7zw** [comment]
I mean, it was back then when I wrote that(and from your screen it seems to work too?) So I don't know what changed about it. But in general, Exordium is on maintenance mode only and only for Vanilla. I'll probably not fix any mod conflict issues at this point.

**Comment by tr7zw** [comment]
I nuked some parts of the description, as the Gui or sign buffering hasn't been a thing for over a year.
