### ISSUE TITLE
Exordium + ImmediatelyFast = flickering bossbars on 1.20.6

### ISSUE THREAD

**Issue by xMelonekMaX** [tr7zw/Exordium#144]
Mods:
fabric-api-0.97.8+1.20.6.jar
exordium-1.2.1-mc1.20.5+unknown.jar (latest commit)
modmenu-10.0.0-beta.1.jar
ImmediatelyFast-Fabric-1.2.14+1.20.6.jar
![image](https://github.com/tr7zw/Exordium/assets/96833801/9bf5b026-cc5b-4bc3-a49c-edafcffa2beb)

**Comment by xMelonekMaX** [comment]
Single bossbar is also flickering

**Comment by Jepl4r** [comment]
@xMelonekMaX I found a workaround while we wait for a bug fix. Toggle the Fast Bossbars option to OFF.
