### ISSUE TITLE
Port to 1.20.6?

### ISSUE THREAD

**Issue by ModxVoldHunter** [tr7zw/Exordium#145]
i think there was some bugs in 1.20.5 but yeah version was out for awhile

**Comment by tr7zw** [comment]
This mod isnt out for 1.20.5 or 1.20.6(they are the same version anyway). Only the dev builds that at this point are entirely untested.

**Comment by ModxVoldHunter** [comment]
> This mod isnt out for 1.20.5 or 1.20.6(they are the same version anyway). Only the dev builds that at this point are entirely untested.

ah
