### ISSUE TITLE
About Minecraft 1.21

### ISSUE THREAD

**Issue by YOMA8338** [tr7zw/Exordium#149]
When will Exordium be ready for 1.21?
If not, are there alternative mods?

**Comment by tr7zw** [comment]
If anyone wants to take the mod and continue updating/developing it, go ahead. I have no plans rn for a 1.21 version/fix issues with old versions.

**Comment by andreasdc** [comment]
One of my favorites mods... Exordium is fundamental and it's a first mod that touched and squeezed the GUI laggy thing (FasterGUI was the original name?). 1.21 is weird in protocol or what hapenned that you don't want to mainain the project? 😿

**Comment by tr7zw** [comment]
Yes, FasterGui was the original name. And I mainly just grew tired of the mod due to conflicts with mods that everyone just keeps complaining about, then performance regressions with for example Immediatly Fast, failed Forge port that ate a ton of time... It's always just issues/used to be better/why not fix xyz. The 1.20.5 build that was pr'd also never made it out to modrinth/curseforge, as even without being released it collected bugs about ui elements flickering with Immediatly Fast.
Doesn't help that I started a full-time job, so have a lot less time to work on mods. This mod was the first one to go inactive.

**Comment by andreasdc** [comment]
> Yes, FasterGui was the original name. And I mainly just grew tired of the mod due to conflicts with mods that everyone just keeps complaining about, then performance regressions with for example Immediatly Fast, failed Forge port that ate a ton of time... It's always just issues/used to be better/why not fix xyz. The 1.20.5 build that was pr'd also never made it out to modrinth/curseforge, as even without being released it collected bugs about ui elements flickering with Immediatly Fast. Doesn't help that I started a full-time job, so have a lot less time to work on mods. This mod was the first one to go inactive.

Someone uses Forge? I think everything is mostly on Fabric nowadays. I think Exordium is fundamental, if it's harder to maintain we should look for someone to help maybe?

**Comment by YOMA8338** [comment]
I am very lightweight thanks to this mod. I would rather not be able to play properly without this mod. I look forward to updates on this mod!

**Comment by andreasdc** [comment]
> I am very lightweight thanks to this mod. I would rather not be able to play properly without this mod. I look forward to updates on this mod!

That's the thing...

**Comment by R00tB33rMan** [comment]
The author assisting with the PRs is a tad busy and will get this mod PRed (likely) in a few weeks. As far as my plans goes towards commissioning this plugin and keeping it alive, I’ll be making this happen to maintain the importance of this mod’s lifecycle (I’ll also look towards having some of these opened issues resolved). As for fixes for older versions, no promises there.

**Comment by tr7zw** [comment]
> The author assisting with the PRs is a tad busy and will get this mod PRed (likely) in a few weeks. As far as my plans goes towards commissioning this plugin and keeping it alive, I’ll be making this happen to maintain the importance of this mod’s lifecycle (I’ll also look towards having some of these opened issues resolved). As for fixes for older versions, no promises there.

For old versions, the correct thing to do would be porting the current mod to my multi-version base. Then the same codebase could be used for 1.18? up to 1.21. But getting the code to this point doesn't sound like fun 😅. Also please contact me in the discord group before getting that PR kicked off. Theres stuff that should be done before more work gets put into the mod.
