### ISSUE TITLE
Small problem with Xaero's minimap

### ISSUE THREAD

**Issue by Julienraptor01** [tr7zw/Exordium#15]
With enabled GUI we can clearly see a small transparent square surrounding the player arrow in the minimap.
The small square isn't always as bright and it kinda flicker.
![image](https://user-images.githubusercontent.com/49841713/181484914-8c60c8c6-27a1-4e9b-a23b-97eabd1aafe1.png)
this doesn't happen with GUI disabled
![image](https://user-images.githubusercontent.com/49841713/181488581-7f152e04-33c5-45ba-8d87-9cea1f854eec.png)
https://youtu.be/81okljsQA0o

**Comment by MopsTMC** [comment]
Still happening on 1.19.2 w/ Exordium 1.0.2 and Xaero's Minimap 23.4.0
It seems to be causing some other transparency issues as well when interacting with beds
![2023-04-22_22 48 15](https://user-images.githubusercontent.com/74558936/233803791-564b4b5f-9256-4987-8885-baaabf3516f7.png)
Leaving the bed momentarily makes many ui elements semi tranparent (hotbar & minimap)
![2023-04-22_22 48 19](https://user-images.githubusercontent.com/74558936/233803794-b2229dd5-eb86-4799-89ac-430baa8814e6.png)

**Comment by tr7zw** [comment]
Currently working on an entirely different working version, that probably will not include the minimap at all.

**Comment by tr7zw** [comment]
The minimap is now excluded by Exordium.
