### ISSUE TITLE
Crash when pressing Tab key on 1.21

### ISSUE THREAD

**Issue by a0916105** [tr7zw/Exordium#152]
https://github.com/tr7zw/Exordium/actions/runs/10229844807
This is working on 1.21, but crashes when pressing Tab key.

> The game crashed whilst unexpected error
> Error: java.lang.AbstractMethodError: Receiver class net.minecraft.class_355 does not define or inherit an implementation of the resolved method 'abstract java.util.List method_48213()' of interface dev.tr7zw.exordium.access.TablistAccess.

**Comment by tr7zw** [comment]
Known issue. 1.21 isn't even released.
