### ISSUE TITLE
Connector Crash 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [tr7zw/Exordium#153]
If there was a crash with the connector, is this a bug with your mod or connector?
Your mod is naturally Forge

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

> -- Head --
> Thread: Render thread
> Suspected Mod: 
> 	Exordium (exordium), Version: 1.2.1
> 		Mixin class: dev.tr7zw.exordium.mixin.GameRendererMixin
> 		Target: net.minecraft.client.renderer.GameRenderer
> 		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.handler$flc000$exordium$reloadShaders(GameRenderer.java:1622)
> Stacktrace:
> 	at net.minecraft.client.renderer.GameRenderer.handler$flc000$exordium$reloadShaders(GameRenderer.java:1622) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:exordium.mixins.json:GameRendererMixin from mod exordium,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_item_rendering.GameRendererMixin from mod modernfix,pl:mixin:APP:exposure-common.mixins.json:DrawViewfinderOverlayMixin from mod exposure,pl:mixin:APP:loot_journal.mixins.json:GameRendererMixin from mod loot_journal,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:darkness.client.json:MixinGameRenderer from mod darkness,pl:mixin:APP:enhancedvisuals.mixins.json:GameRendererMixin from mod enhancedvisuals,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:corgilib-common.mixins.json:client.GameRendererMixin from mod corgilib,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod embeddium_extra,pl:mixin:APP:mixins.nonvflash.json:GameRendererMixin from mod no_nv_flash,pl:mixin:APP:sanitydim.mixins.json:MixinGameRenderer from mod sanitydim,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor from mod (unknown),pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer.m_172767_(GameRenderer.java:630) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:exordium.mixins.json:GameRendererMixin from mod exordium,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:pehkui.mixins.json:reach.client.compat1202minus.GameRendererMixin from mod pehkui,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_item_rendering.GameRendererMixin from mod modernfix,pl:mixin:APP:exposure-common.mixins.json:DrawViewfinderOverlayMixin from mod exposure,pl:mixin:APP:loot_journal.mixins.json:GameRendererMixin from mod loot_journal,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:darkness.client.json:MixinGameRenderer from mod darkness,pl:mixin:APP:enhancedvisuals.mixins.json:GameRendererMixin from mod enhancedvisuals,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:corgilib-common.mixins.json:client.GameRendererMixin from mod corgilib,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:client.compat1204minus.compat1193plus.GameRendererMixin from mod pehkui,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod embeddium_extra,pl:mixin:APP:mixins.nonvflash.json:GameRendererMixin from mod no_nv_flash,pl:mixin:APP:sanitydim.mixins.json:MixinGameRenderer from mod sanitydim,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:APP:forge-badoptimizations.mixins.json:accessor.GameRendererAccessor from mod (unknown),pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinGameRenderer from mod (unknown),pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.renderer.GameRenderer$1.m_5787_(GameRenderer.java:379) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:classloading,pl:connector_pre_launch:A}
> 	at net.minecraft.client.renderer.GameRenderer$1.m_5787_(GameRenderer.java:357) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:classloading,pl:connector_pre_launch:A}
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-conditions-api-v1.mixins.json:SinglePreparationResourceReloaderMixin from mod fabric_resource_conditions_api_v1,pl:mixin:APP:moonlight.mixins.json:ConditionHackMixin from mod moonlight,pl:mixin:A,pl:connector_pre_launch:A}
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
> 	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.SimpleReloadInstanceMixin from mod modernfix,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric_resource_loader_v0,pl:mixin:APP:blueprint.mixins.json:SimpleReloadInstanceMixin from mod blueprint,pl:mixin:A,pl:connector_pre_launch:A}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A,pl:connector_pre_launch:A}
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:computing_frames,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23880!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A,pl:connector_pre_launch:A}

**Comment by tr7zw** [comment]
There is no Forge version and Connector will never be supported.
