### ISSUE TITLE
Incompatibility with Bedrockify (Can't launch)

### ISSUE THREAD

**Issue by dreamy32** [tr7zw/Exordium#154]
Since the UI has undergone many changes with the mod Bedrockify, it's understandable that there are some issues.

Bedrockify on Modrinth: https://modrinth.com/mod/bedrockify/version/3nHbIP4m

**Comment by tr7zw** [comment]
Note that ui mods are explicitly not supported. This mod is only designed for the vanilla ui.

**Comment by tr7zw** [comment]
#159
