### ISSUE TITLE
What does enableNametagScreenBuffering in Exordium options mean?

### ISSUE THREAD

**Issue by TechPro424** [tr7zw/Exordium#19]
What does `enableNametagScreenBuffering` in Exordium options mean?

**Comment by tr7zw** [comment]
It basically renders the nametags only x times per second. Ofc this causes some stuttering of the nametags when moving the camera, so it's disabled by default. Probably primarily interesting for game server lobbies like Hypixel or Cubecraft.

Also why the translation key, it should show up with the correct name "Enable Nametag Buffering"?

**Comment by TechPro424** [comment]
yes, it did, but I still did not know what it meant.
anyway, thanks for the clarification!
