### ISSUE TITLE
Crosshair and damage indicator are opaque

### ISSUE THREAD

**Issue by Madis0** [tr7zw/Exordium#22]
![2022-09-28_19 59 44](https://user-images.githubusercontent.com/8611110/192844293-374f34e1-802c-40c8-a194-b82eb0602c14.png)

Exordium v1.0.0 and v1.0.1, Fabric API 0.62.0, MC 1.19.2, Fabric Loader 0.14.9

**Comment by tr7zw** [comment]
Hm thinking about it. This one might not be fixable. They are not transparent, they invert the color I think. I can't replicate that, having them part of the rendering like that. Will have to check what can be done.

**Comment by Madis0** [comment]
I think it should just be a different blending mode, that's how it works on images (e.g. try creating a layer on GIMP and changing its blend mode)

**Comment by tr7zw** [comment]
Yes, but since it's part of the everything right now, can't exactly just do that. Might need to relocate the draws to outside the buffer logic.
