### ISSUE TITLE
[Incompatability] Fabrication (Config Screen)

### ISSUE THREAD

**Issue by Infinidoge** [tr7zw/Exordium#26]
[Fabrication](https://modrinth.com/mod/fabrication) ([Repository](https://github.com/unascribed/Fabrication/)) has a custom configuration screen which has a number of animations.
With Exordium installed, these animations predictably become choppy due to the changed FPS.

Disabling the mod for Screens removes the choppiness.

I wasn't sure if you could use some kind of screen blacklist or something, but thought to report it here regardless.

**Comment by tr7zw** [comment]
I'll by default disable the screen logic in the next release since it does more harm than good.
