### ISSUE TITLE
Pause menu darkening overlay flickers when F1 is enabled.

### ISSUE THREAD

**Issue by sisby-folk** [tr7zw/Exordium#28]
Dark overlay constantly flickers between darker and lighter with F1 enabled. 
Screenshot shown with sodium

![javaw_KgcyhUwOgr](https://user-images.githubusercontent.com/55819817/194235997-9d7a768f-0f21-42a1-9477-49299b56df8a.png)
![javaw_Z31NXhWfJM](https://user-images.githubusercontent.com/55819817/194235998-596235cf-5323-4a43-b347-160f661ce853.png)

Pretty bad visual strain / risk.

Let me know if it's not easy to reproduce, I'll nail it down if it's an incompatibility.

**Comment by Spacebarium** [comment]
I would like to add that this now extends to all GUIs when F1 is enabled

https://youtu.be/e_WFOgo00BI

**Comment by tr7zw** [comment]
Fixed in 1.1.0+.
