### ISSUE TITLE
crosshair has no blend mode

### ISSUE THREAD

**Issue by I-like-Portal-2** [tr7zw/Exordium#36]
In the vanilla, the crosshair and the attack indicator have some sort of blending, however, with this mod, when GUI is enabled, the crosshair is always white.
Vanila:
![how_it_should_be](https://user-images.githubusercontent.com/99472757/200298306-16a8f6e3-0fc0-4ac7-a84e-692ef0e66a41.png)
With Exordium:
![how_it_appears](https://user-images.githubusercontent.com/99472757/200298311-b99dece5-9ac4-4cf2-a7bb-a5f8ca19102c.png)
Is there any way to change it? Thanks!

**Comment by tr7zw** [comment]
Duplicate #22

**Comment by DeadbushCarrot** [comment]
I liked it like that sucks me!
