### ISSUE TITLE
Rendering Bug when laying in a bed

### ISSUE THREAD

**Issue by KingContaria** [tr7zw/Exordium#38]
Hi,
i was using Exordium 1.0.2 in 1.19.2 and noticed the hotbar gets brighter/translucent when sleeping in a bed.
Upon exiting the bed, its rendered very bright for a moment, then goes back to its correct color.

Here is a video showcasing it:
https://youtu.be/HtNc3N6Q6SQ

~These are the mods im using:~ was able to reproduce the bug with just exordium and fabric api

If you can't reproduce the issue i would be glad to help find the cause :)

**Comment by ButterDebugger** [comment]
This bug is still persistent in 1.19.3 and additionally has the same effect not just on the hotbar but also on bossbars

**Comment by tr7zw** [comment]
Yea, currently working on the other mods and since this isn't something game-breaking, I haven't gotten around to it yet.

**Comment by tr7zw** [comment]
Fixed in 1.1.0+.
