### ISSUE TITLE
flickering left side panel 1.18.2 (with mod Inventorio)

### ISSUE THREAD

**Issue by Fwexzy** [tr7zw/Exordium#39]
if you turn off the render gui everything is fine.

Enabled gui turned off![2022-11-16_14 44 31](https://user-images.githubusercontent.com/118065267/202093981-0f2830e2-e4df-4ac7-8489-21760ed84503.png)
Enabled gui on (very fast flickering(you can see what's in the slots but the flickering is annoying))![2022-11-16_14 46 44](https://user-images.githubusercontent.com/118065267/202094241-40423f5d-303e-4cab-b5c5-4d3aea2738d3.png)

**Comment by ConqAra** [comment]
can confirm, the little bar on the left of hotbar flickers when having exordium render gui setting enabled

**Comment by tr7zw** [comment]
Then they are not compatible with each other. Just remove Exordium.

**Comment by tr7zw** [comment]
Fixed by not having other mods being part of Exordium's buffering.
