### ISSUE TITLE
Release on Modrinth/Curseforge?

### ISSUE THREAD

**Issue by Zensonaton** [tr7zw/Exordium#4]
I think that this mod deserves some popularity, so releasing this mod on Modrinth or/and Curseforge would make it easier for people to notice and use! :+1:

**Comment by tr7zw** [comment]
The mod is not yet in a state for that. Currently working on the 2 branches containing the Sign and potentially Nametag optimizations (#3 ) , also the enchant glow seems to be messed up again.

**Comment by tr7zw** [comment]
https://www.curseforge.com/minecraft/mc-mods/exordium
https://modrinth.com/mod/exordium
