### ISSUE TITLE
Make 1.19.3 updates compatible with all 1.19 versions?

### ISSUE THREAD

**Issue by VeggeieDude** [tr7zw/Exordium#44]
Hi, I'm currently using 1.19.2 until other mods catch up to updating to 1.19.3. That may be a while, so I was wondering if you'd be willing to make the newest updates compatible with all 1.19 versions, or at least 1.19.2

**Comment by tr7zw** [comment]
Maybe, right now I'm not really working on this mod at all, more on other mods. I can already say that there won't be any version that works with 1.19.3 and 1.19.2, due to the internal changes. I guess the bigger question will be 1.18.

**Comment by VeggeieDude** [comment]
Ahh ok, gotcha. Ty!
