### ISSUE TITLE
Hanging Sign Text rendering above

### ISSUE THREAD

**Issue by Con5ole1** [tr7zw/Exordium#45]
Description:
Hi I completly understand if this is unsupported or cannot be fixed since this is to do with the 1.20 experimental datapack but just to let you know hanging signs text is hovering above the sign

Mods:
Fabric-api-0.69.1+1.19.3
Exordium-fabric-1.0.3-mc1.19.3

Image:
![2022-12-18_12 17 07](https://user-images.githubusercontent.com/58005153/208298058-89c4b1cd-5fda-4096-8e9e-751ae5e7bfe8.png)

**Comment by tr7zw** [comment]
Ah crap, I forgot to check the hanging signs.
