### ISSUE TITLE
Sign buffering reduces HD font quality

### ISSUE THREAD

**Issue by Madis0** [tr7zw/Exordium#48]
Enabling sign buffering reduces the quality of an HD TTF font, such as [Roboto Bold](https://www.curseforge.com/minecraft/texture-packs/hd-font-roboto-bold).

![2022-12-23_21 23 59](https://user-images.githubusercontent.com/8611110/209397038-780c4be2-334b-43ee-b589-9088f5b06598.png)

![2022-12-23_21 24 18](https://user-images.githubusercontent.com/8611110/209397016-5abee7b7-e459-40c1-8ce6-b828a9da0dcc.png)

**Comment by tr7zw** [comment]
Intended. The Buffer texture size is meant for vanilla/blocky fonts. Disable the sign buffering when playing with hd fonts.

**Comment by bluebear94** [comment]
> Intended. The Buffer texture size is meant for vanilla/blocky fonts. Disable the sign buffering when playing with hd fonts.

Could this be documented in the mod description’s FAQ?

**Comment by tr7zw** [comment]
I can update the FAQ to clarify that some mod support/Forge/high-res texture packs are not planned and probably will never work.
