### ISSUE TITLE
Fix fabrication menus 

### ISSUE THREAD

**Issue by Kamillaova** [tr7zw/Exordium#50]
https://user-images.githubusercontent.com/54859825/210141514-d076c5e1-94ad-430d-938b-6a74f4f94939.mp4

possible solution: add user-configurable exclusions for menus

**Comment by tr7zw** [comment]
Menu buffering isn't even inside the newest versions anymore (well it is, but only visible in the config file). No updates to fix issues with other mods for this removed feature are planed.

**Comment by Kamillaova** [comment]
> Menu buffering isn't even inside the newest versions anymore (well it is, but only visible in the config file). No updates to fix issues with other mods for this removed feature are planed.

ah, okay
