### ISSUE TITLE
Voxelmap is incompatible

### ISSUE THREAD

**Issue by IF-desu** [tr7zw/Exordium#52]
In1.18.2,if I enabled "enable GUI" all the gui includedhotbar,minihud,minimap will be disappeared
![H 8Z_T_(L`D0 QN7JO`@~{2](https://user-images.githubusercontent.com/86994398/211024597-7701c4e2-258f-4c7b-9d25-e0792dd0e5e6.png)
I'm sure that if "enable GUI"is diaabled All the GUI will be shown normally

**Comment by cbg520666** [comment]
not included minimap(

**Comment by tr7zw** [comment]
Then you have some incompatible mod installed.

**Comment by cbg520666** [comment]
> Then you have some incompatible mod installed.
This is my modlist,Please read and find which mod is incompatible 
AllMusic-2.12.5-all.jar
amecs-1.3.8+mc.1.18.2.jar
architectury-4.1.34.jar
badpackets-fabric-0.1.2.jar
betterfpsdist-fabric-1.18-1.7.jar
betterfpsdist-fabric-1.18-1.8.jar
BetterPingDisplay-Fabric-1.18.2-1.1.1.jar
Bookshelf-Fabric-1.18.2-13.0.7.jar
clickthrough-1.18.2-fabric0.47.10-0.4.jar
cloth-config-6.2.57-fabric.jar
exordium-fabric-1.0.1-mc1.18.2.jar
fabric-api-0.48.0+1.18.2.jar
fabrication-3.1.3+1.18.jar
fancymenu_fabric_2.6.4_MC_1.18.2.jar
held-item-info-1.2.0-1.18.2.jar
iris-mc1.18.2-1.2.2-build.32.jar
konkrete_fabric_1.3.3_MC_1.18-1.18.1.jar
KronHUD-2.0.4.jar
Ksyxis-1.1.jar
language-reload-1.2.1.jar
litematica-fabric-1.18.2-0.11.3.jar
magiclib-0.5.37.jar
MasaGadget-3.0.0 (1).jar
moreculling-1.18.2-0.8.2.jar
NoFog-1.3.1_1.16.5-1.19.2-fabric.jar
replaymod-1.18.2-2.6.5.jar
rer-2.5.0.jar
RoughlyEnoughItems-8.0.442.jar
simpleshulkerpreview-1.18.x-v2.1.jar
slotlock-1.1.1-BETA+1.18.jar
smoothboot-fabric-1.18.2-1.7.0.jar
sodium-fabric-mc1.18.2-0.4.1+replaymod.rev.23e83a1.jar
starlight-1.0.2+fabric.89b8d9f.jar
torohealth-1.18-fabric-2.jar
tweakermore-mc1.18.2-v3.6.1.jar
tweakeroo-fabric-1.18.2-0.13.3.jar
TweakMyClient-1.18.2-3.4.291+5ae910f-beta.jar
vector-addon-0.3.4.jar
viafabric-0.4.9+21-main.jar
voxelmap-1.18.2-1.11.2.jar
wthit-fabric-4.13.2.jar
[C键缩放]WI-Zoom-1.3-MC1.18.jar
[fabirc-1.18.1-1.19]AllMusic-2.5.12.jar
[FPS减速器] FpsReducer2-fabric-1.18.2-2.0.jar
[masa前置]malilib-fabric-1.18.2-0.12.0.jar
[REI物品管理器]RoughlyEnoughItems-8.0.441.jar
[R键整理]InventoryProfilesNext-fabric-1.18.2-1.3.5.jar
[sodium拓展]sodium-extra-mc1.18.2-0.4.2.jar
[创世神]worldedit-fabric-mc1.18.2-7.2.10-SNAPSHOT-dist.jar
[地毯]fabric-carpet-1.18.2-1.4.66+v220228.jar
[地毯客户端附属]essential-client-1.18.2-1.1.6.jar
[地毯附属]carpet-extra-1.18.2-pre2-1.4.64.jar
[实体渲染优化]EntityCulling-Fabric-1.3.3.jar
[快速村民交易]easiervillagertrading-1.18-fabric0.43.1-1.5.4.jar
[懒狗破基岩]bedrock-miner-1.0.0-1.18.2.jar
[投影打印机zhaixianyu二改05_06]litematica-printer-1.18.2-2.3.jar
[按键冲突显示]Controlling-fabric-1.18.2-9.0+17.jar
[挖掘工具显示]can-i-mine-this-block-1.2.0.jar
[方块实体优化]enhancedblockentities-0.51.18.jar
[更多动画] notenoughanimations-fabric-1.5.0-mc1.18.2.jar
[标题]RandomTitle-Fabric-1.0.7.jar
[模组菜单] modmenu-3.1.0.jar
[游戏内账号切换]InGameAccountSwitcher-Fabric-1.18-7.1.3.jar
[滚轮滑动物品]itemscroller-fabric-1.18.2-0.16.0.jar
[物品栏HUD+] InventoryHUD-fabric-[1.18] -3.4.2.jar
[疾速加载] dashloader-def-3.0.1+1.18.jar
[聊天头像显示]chat_heads-0.5.1-fabric-1.18.jar
[自动第三人称视角]auto_third_person-1.18-1.1.0.jar
[自动钓鱼]Autofish-0.9.4-fabric-mc1.18.jar
[自定义选择框]CustomSelectionBox-5.1.0.jar
[船图显示]Boat-Item-View-Fabric-1.18-0.0.3.jar
[苹果皮] appleskin-fabric-mc1.18.2-2.4.0.jar
[蜂巢工具提示] beehive-tooltips-fabric-1.4.2.jar
[迷你F3]minihud-fabric-1.18.2-0.22.0.jar
[锂]lithium-fabric-mc1.18.2-0.7.9.jar
[附魔描述] EnchantmentDescriptions-Fabric-1.18.2-10.0.2.jar
[鼠标手势] MouseTweaks-fabric-mc1.18-2.22.jar
共享投影syncmatica-1.18.2-0.3.2.jar

**Comment by tr7zw** [comment]
Honestly, just remove this mod instead.

**Comment by IF-desu** [comment]
should i upload the game log?

**Comment by tr7zw** [comment]
No, that won't help. You have some incompatible mod in there, and there are soo many UI mods, just remove this mod. This mod will never work with all mods, and with your amount of UI modifications, it's better to just remove it.

**Comment by IF-desu** [comment]
To my surprise the reason is Mod"Voxelmap",I just replaced this mod with Xaeromap then enabled "enable GUI",all the gui didn't disapperd :),I also test this in MCversion 1.19.2,save satuation happend:(

**Comment by tr7zw** [comment]
Odd, I never tested Voxelmap, just assumed it would work since Xaero works.

**Comment by dlfnn** [comment]
By the way I tried to fix this bug before and it works pretty well.
Just make a resourcepack to whipe off all the semi-translucent pixels, and you are good to go!
