### ISSUE TITLE
[Issue]  Exordium makes Origins selection screen be a bit slow

### ISSUE THREAD

**Issue by NordicGamerFE** [tr7zw/Exordium#54]
Everything should be stated in the title

**Comment by NordicGamerFE** [comment]
should mention that on curseforge since origins is a widely used mod

**Comment by tr7zw** [comment]
No clue what Origins is, but the main point is, that buffering screens has been turned off by default for a while, and entirely removed from 1.19.3.

**Comment by NordicGamerFE** [comment]
Thank you for the quick reply and great help, highly appreciated. [Origins](https://www.curseforge.com/minecraft/mc-mods/origins) is the mod that lets you pick between a bunch of options when you first start a world like fox, iron golem etc.
