### ISSUE TITLE
Spy glass UI slowed down and zooms in indefinitely

### ISSUE THREAD

**Issue by Andre601** [tr7zw/Exordium#55]
When using this mod does the Spyglass' UI zoom in at a much smaller speed than it should (See video).
Additionally does it seem like it zooms in indefinitely, resulting in the glass texture zooming in more than it actually should by default.

https://user-images.githubusercontent.com/11576465/216977166-7118ff10-7a7c-4c79-8770-d1813e3cd789.mp4

**Comment by tr7zw** [comment]
Just tested it, the final UI texture zoom is correct, just the timing is wrong. Looks like it uses draw calls for the animation, instead of ticks 👀

**Comment by tr7zw** [comment]
Fixed by not having the spyglass buffered at all.
