### ISSUE TITLE
Transparent sign text pixels are completely removed while using sign bufffer

### ISSUE THREAD

**Issue by BuggyAl** [tr7zw/Exordium#56]
I am using the **[Geometric Font 1.1](https://cdn.modrinth.com/data/hIdXd06Y/versions/geakBimu/Geo%20Font%201.1%20Scale%202.zip)** font pack which contains some semi-transparent pixels in the letters. While using sign buffering, the transparent pixels are completely removed and are seethrough.

**Without Sign Buffering**
![image](https://user-images.githubusercontent.com/64368488/221386664-d6eae9ec-5e6d-434e-acf3-9aea45ae2552.png)

**With Sign Buffering**
![image](https://user-images.githubusercontent.com/64368488/221386597-28c06f5f-4ae7-42f6-8528-1ccea4bb7fe9.png)

**Comment by tr7zw** [comment]
Hm might be a wrong setting on the blend mode during the buffered rendering. Also note, that only the vanilla font is really intended to work this with. Things like HD fonts will look broken either way. But this one might work with the transparency fixed.
