### ISSUE TITLE
Incompatibility with Cobblemon

### ISSUE THREAD

**Issue by ahribellah** [tr7zw/Exordium#57]
Using Exordium v1.0.2 (because Cobblemon is only available on 1.19.2) and Cobblemon at the same time causes the game to instantly crash when the Cobblemon client is initialized.

Sample crash log: https://mclo.gs/pRKKytF

**Comment by tr7zw** [comment]
Looking at the mod page, there is no chance for them to work well together anyway. This mod can't ensure much mod compatibility, and the more complex the hud is, the worse. Best case leave out this mod.
