### ISSUE TITLE
[1.19.4] Incompatibility with Dynamic Crosshair mod: Inventory screen and gamemode selector screen flicker while both are installed.

### ISSUE THREAD

**Issue by pixlxip** [tr7zw/Exordium#58]
[Screencast from 2023-03-17 16-31-28.webm](https://user-images.githubusercontent.com/99521063/226130047-9063374c-d1bb-4aaf-b9c7-a91aadf89049.webm)
See in this video ^

This happens on both Fabric and Quilt

Steps to reproduce:
Install Fabric or Quilt Loader
Install Fabric API or Quilt Standard Libraries
Install Exordium, Cloth Config, and Dynamic Crosshair
Launch Minecraft
Open or create a world
Open you inventory

**Comment by iiPythonx** [comment]
Having the exact same issue with Exordium 1.0.3 and Dynamic Crosshair 5.3.1 on Quilt.  
It would be nice to see this looked into if at all possible, it makes playing the game with both mods installed pretty challenging (at least for me, as my eyes don't exactly like having a mini strobe light appear everytime I open my inventory).

**Comment by tr7zw** [comment]
Probably just remove this mod for now when using Dynamic Crosshair. Currently a rewrite is in the works, that may make mods like Dynamic Crosshair compatible.

**Comment by tr7zw** [comment]
Fixed by 1.1.x by not buffering these parts at all.
