### ISSUE TITLE
[1.19.3] Incompatibility with Wynntils: Spell cast overlay turns hud half transparent

### ISSUE THREAD

**Issue by Commander07** [tr7zw/Exordium#59]
Expected results:
https://user-images.githubusercontent.com/45269106/230149772-173905ea-466a-4a0d-a233-a33c3ad0780a.mp4

Actual results:
https://user-images.githubusercontent.com/45269106/230149799-53ec6389-4608-4a4d-92df-6c1e83b49e1f.mp4

Steps to reproduce:
- Install both Exordium and Wynntils
- Join Wynncraft cast any spell
- Observe

**Comment by tr7zw** [comment]
Just FYI, mod compatibility with other mods will not be worked on till after the next update(whenever I get around to that).

**Comment by Frontear** [comment]
can confirm, the aura spell of shaman is affected by exordium. Good to know it'll eventually be tackled though

**Comment by tr7zw** [comment]
Currently working on that new version. For people on 1.19.4 they can technically test that version by downloading it from the actions tab ( https://github.com/tr7zw/Exordium/actions?query=branch%3A1.19.4-dev ). So far I have done 0 testing on how it compares to the current release or mod compatibility. Maybe it's better, maybe it's worse.

**Comment by Commander07** [comment]
Tested [this](https://github.com/tr7zw/Exordium/actions/runs/4801454614) version and the incompatibility is gone.

**Comment by tr7zw** [comment]
#159
