### ISSUE TITLE
Increase chat refresh rate after opening it

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/Exordium#60]
I think it would be nice suggestion, because you don't need high refresh rate when chat is not opened/focused.

**Comment by tr7zw** [comment]
The chat is static. Why increate the refresh rate?

**Comment by andreasdc** [comment]
For smoother scrolling

**Comment by tr7zw** [comment]
I mean, the chat teleports when scrolling, but a good point to do an asap refresh once the scroll position and shown one don't line up.

**Comment by andreasdc** [comment]
That would be epic :)

**Comment by tr7zw** [comment]
Currently working on getting the big update out for ItemSwapper. Exordium is next on my list for big update/rework.

**Comment by itsTyrion** [comment]
With the latest update, text in the obfuscated style is completely static if "force chat updates" is off

**Comment by tr7zw** [comment]
Yea, thats somewhat wanted. The obfuscated text is not usually used, and has been ignored by this mod the entire time so far (also not working on signs).

**Comment by tr7zw** [comment]
Shouldn't be an issue anymore with 1.1.0+.
