### ISSUE TITLE
Blinking buttons when hover from other plugin in inventory.

### ISSUE THREAD

**Issue by xhaooy** [tr7zw/Exordium#61]
here is my issue created for that other plugin: https://github.com/blackd/Inventory-Profiles/issues/319

all buttons related to this mod(inventory profiles) blink when hover(in inventory, crafting table)

apparently version for minecraft 1.19.2 is affected but 1.19.4 works fine.

**Comment by tr7zw** [comment]
The one saying "Enable Screens"

**Comment by xhaooy** [comment]
blinking removed, thank you!
