### ISSUE TITLE
Rendering screen java.util.NoSuchElementException causes crash

### ISSUE THREAD

**Issue by LichLord91** [tr7zw/Exordium#62]
originally logged here: 
https://github.com/blackd/Inventory-Profiles/issues/321

I was advised that the actual issue may be with Exordium or Sodium after disabling Exordium plugin it seems like its no longer crashing. 

Here's log file with all the info

https://mclo.gs/YgRqG6i

**Comment by tr7zw** [comment]
Currently rewriting the mod, not gonna look into this(also looks like a mess, since something emptied the stack, so probably a mod conflict skipping some mixin).

**Comment by tr7zw** [comment]
Ok also added that this is about screen buffering(which has been disabled/removed for some time), this has become a non-issue.
