### ISSUE TITLE
1.19.4 Fabric Incompatibility with Memory Leak Fix

### ISSUE THREAD

**Issue by LeeFerreira** [tr7zw/Exordium#69]
Minecraft Version 1.19.4, modloader Quilt 0.19.0-beta.18. Exordium 1.1.0-1.19.4 Fabric causes crashing with Memory Leak Fix 1.0.0 (troubleshooted with assistance from the Quilt forums).
https://pastebin.com/pS8YdM1B

**Comment by LeeFerreira** [comment]
Disregard last - Quilt specific bug. Apologies.

**Comment by tr7zw** [comment]
Was about to say, that crash log seems to have nothing to do with Exordium.
