### ISSUE TITLE
Version 1.1.0 not rendering text on signs

### ISSUE THREAD

**Issue by AndrewN04** [tr7zw/Exordium#70]
Tried testing the latest version and noticed that signs were not rendering text. 
I went through all my mods on prism and disable them and enabled them until it appeared again.
Sign rendering works with any other version of Exordium.

Just wanted to let you know.

**Comment by tr7zw** [comment]
Sign rendering was unchanged compared to the last version, so that's cool I guess. Did you have sign buffering on in the settings?

**Comment by AndrewN04** [comment]
I didn't change anything, I actually had to disable sign buffering to see the sign text, so I'm not sure what is going on.

**Comment by tr7zw** [comment]
So yes, you had it on. Good to know, will test. Also, provide the other mods you have installed.

**Comment by AndrewN04** [comment]
Mega link containing all the mods I'm using, made this recently to send to my friend because he was to lazy to download them himself: https://mega.nz/folder/sZNxhDpL#ANvAZbDXk6LtH_eA_05myQ
I switched it to 1.0.3 in the link, I use all the mods in the main directory and the optional mods directory.

**Comment by LichLord91** [comment]
+1 on signs not rendering text on 1.1.0

**Comment by tr7zw** [comment]
Ok found the issue. Accidentally removed one too many things, which removed the entire "late render" logic. That logic is used to render the sign texture/render buffered nametags to the screen. My bad.
