### ISSUE TITLE
1.1.0 seems to be no longer working with certain mods

### ISSUE THREAD

**Issue by Longie520** [tr7zw/Exordium#73]
Not sure what exact mods no longer work with 1.1.0, but in my case, the Inventory HUD was no longer working under Exordium, as the HUD renders at full fps, and there's a significant fps increase when I turn the HUD off

Not sure if the change should be intentional, but if there's no fix for this issue I'm still happy with the fps boost :D

**Comment by tr7zw** [comment]
You mean the hotbar? Or the inventory screen? Other mods? How do you know that the hotbar renders at full speed? Have you checked the settings?

**Comment by Longie520** [comment]
> You mean the hotbar? Or the inventory screen? Other mods? How do you know that the hotbar renders at full speed? Have you checked the settings?

I meant the HUD screen from the mod [Inventory HUD](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge) (see the attachment). I optimized all my settings so that it rendered everything at minimum fps, however the HUD was animating at full fps (the difference is that it looked smooth)
<img width="114" alt="Screenshot 2023-06-01 at 18 02 47" src="https://github.com/tr7zw/Exordium/assets/117007831/bfb3dc25-3153-4bf6-b406-1471c784800b">
