### ISSUE TITLE
Item cooldowns don't rebuffer the hotbar

### ISSUE THREAD

**Issue by VidTu** [tr7zw/Exordium#75]
Cooldowns set to items like ender pearls aren't updating the hotbar.
Note that custom servers can set the cooldown for any item type.

https://github.com/tr7zw/Exordium/assets/60929459/25b0a016-9a1c-4fa6-be8a-d6250d448d42

**Comment by tr7zw** [comment]
Good point. Will fix that together with the enchant glint(kinda forgot about that too).

**Comment by x-yingcan-x** [comment]
Item animtions don't work well in hotbar (as the cooldown)
I think it's the same problem ( and I'm lazy to open new one )

**Comment by tr7zw** [comment]
Already fixed in the latest commit, forgot to close this.

**Comment by x-yingcan-x** [comment]
I tried [this build](https://github.com/tr7zw/Exordium/actions/runs/5160093029)
By my test, to let it works well, you need to let it buffer once after something start cooldown.

**Comment by tr7zw** [comment]
What do you mean? That build refreshes at the settings fps as long as you have a cooldown active or enchanted item in the hotbar.

**Comment by x-yingcan-x** [comment]
but it doesn't refresh
