### ISSUE TITLE
Please make 1.16.5 version

### ISSUE THREAD

**Issue by K4sum1** [tr7zw/Exordium#87]
I've found the 1.18.2 version works on 1.17.1 with the version limit removed, but it crashes 1.16.5 at launch. I like 1.16.5 since it performs the best out of 1.12, 1.16, 1.17, and 1.18 on my machine. I would like to have this mod there to further improve it's performance.

**Comment by tr7zw** [comment]
Not possible*, missing the requirements from mcs side. Also not interested in creating a 1.16 version.
*without a ton more work than in later versions.

**Comment by K4sum1** [comment]
least lazy mc mod dev
