### ISSUE TITLE
Not compatible with Enhanced Block Entities

### ISSUE THREAD

**Issue by MarkusWy** [tr7zw/Exordium#90]
The game crashed upon loading a world, and I get this error.

```
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.exordium.access.SignBufferHolder.renderBuffered(net.minecraft.class_4587, net.minecraft.class_4597, boolean, int)" because "this.renderingSign" is null
```

Either mod works alone, but with each other this crash happens.

This is rather unfortunate since both of these mods are important performance enhancers for me.

I have decided to only use EBE until this is fixed since it has a slightly higher FPS impact for me in my world than Exordium.

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/Exordium/assets/5133936/147a465d-4281-4b71-9343-1edf840e07f4)

**Comment by MarkusWy** [comment]
Sorry, missed that. I did look for a mention of EBE, but should have looked more
