### ISSUE TITLE
Crash when rendering Signs

### ISSUE THREAD

**Issue by ItzRobles** [tr7zw/Exordium#91]
When I disable Exordium it can play without problems, I have checked the logs and it is due to a failure to render signs.
1.20.1

https://mclo.gs/JHTqTn6

Mods:
  [✔] AmbientSounds_FABRIC_v5.2.20_mc1.20.1
  [✔] antighost-1.20-fabric0.83.0-1.1.5
  [✔] authme-7.0.2+1.20
  [✔] Boat-Item-View-Fabric-1.20.1-0.0.5
  [✔] capes-1.5.2+1.20-fabric
  [✔] carpet-extra-1.20-1.4.115
  [✔] carpet-fixes-1.20-1.16.1
  [✔] chat_heads-0.10.18-fabric-1.20
  [✔] cherishedworlds-fabric-6.1.1+1.20.1
  [✔] ClearDespawn-fabric-1.20.1-1.1.13
  [✔] cloth-config-11.1.106-fabric
  [✔] completeconfig-2.5.0
  [✔] continuity-3.0.0-beta.3+1.20.1
  [✔] CreativeCore_FABRIC_v2.10.28_mc1.20.1
  [✔] dashloader-5.0.0-beta.1+1.20.0
  [✔] DCCH-2.0+1.17
  [✔] Debugify-1.20.1+2.0
  [✔] DetailArmorBar-2.6.3+1.20.1-fabric
  [✔] dynamic-fps-2.4.0
  [✔] eating-animation-1.9.4+1.20
  [✔] enhancedblockentities-0.9+1.20
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] Essential-fabric_1-19
  [✔] exordium-fabric-1.1.3-mc1.20.1
  [✔] fabric-api-0.86.1+1.20.1
  [✔] fabric-carpet-1.20-1.4.112+v230608
  [✔] fabric-language-kotlin-1.10.8+kotlin.1.9.0
  [✔] fabricskyboxes-0.7.2+mc1.20.1
  [✔] fallingleaves-1.15.2+1.20.1
  [✔] ferritecore-6.0.0-fabric
  [✔] forcecloseloadingscreen-2.1.1
  [✔] fsb-interop-1.3.3+mc1.20-build.46
  [✔] ImmediatelyFast-1.1.20+1.20.1
  [✔] indium-1.0.21+mc1.20.1
  [✔] iris-mc1.20-1.6.4
  [✔] itemscroller-fabric-1.20.1-0.20.0
  [✔] krypton-0.2.3
  [✔] lazydfu-0.1.3
  [✔] LetSleepingDogsLie-1.20.1-Fabric-1.2.0
  [✔] litematica-fabric-1.20.1-0.15.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] Log-Begone-Fabric-1.20.1-1.0.8
  [✔] lunade-fastanim-1.6-1.20
  [✔] malilib-fabric-1.20.1-0.16.1
  [✔] mcwifipnp-1.6.5-1.20-fabric
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] microdurability-0.3.6+1.20
  [✔] midnightlib-fabric-1.4.1.1
  [✔] minihud-fabric-1.20.1-0.27.0
  [✔] MixinConflictHelper-1.2.0
  [✔] modelfix-1.14-fabric
  [✔] modmenu-7.2.1
  [✔] morechathistory-1.19.1-1.1.1
  [✔] moreculling-1.20-0.18.1
  [✔] no-telemetry-1.7.0
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] Notes-1.20.1-2.1.0-fabric
  [✔] ocrenderfix_sodium-fabric-1.2.0
  [✔] onsoulfire-1.20.1
  [✔] puzzle-1.5.2+1.20
  [✔] reeses_sodium_options-1.6.3+mc1.20.1-build.92
  [✔] Rrls-1.20.1-3.1.0-fabric
  [✔] screenshot-to-clipboard-1.0.9-fabric
  [✔] sodium-extra-0.4.23+mc1.20.1-build.106
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] sodium-shadowy-path-blocks-3.1.0
  [✔] status-effect-bars-1.0.3
  [✔] stendhal-1.3.9-1.20
  [✔] syncmatica-1.20.1-0.3.10
  [✔] threadtweak-fabric-1.20.1-0.1.0
  [✔] tooltipfix-1.1.1-1.20
  [✔] tweakermore-mc1.20.1-v3.14.0
  [✔] tweakeroo-fabric-1.20.1-0.17.1
  [✔] viafabricplus-2.8.2
  [✔] vt-downloader-2.0.7+1.20.1
  [✔] Xaeros_Minimap_23.6.0_Fabric_1.20
  [✔] XaerosWorldMap_1.31.0_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.1.0+1.20
  [✔] yosbr-0.1.2

**Comment by tr7zw** [comment]
enhancedblockentities, see the description of this release/other already closed issues. Turn off sign buffering.
