### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by RazerLemon** [tr7zw/Exordium#93]
whenever i join a server for example on pvp legacy my game crashes but when I join a server without a scoreboard it doesnt crash

**Comment by tr7zw** [comment]
Can't do anything without the crash report.

**Comment by RazerLemon** [comment]
this is the whole crash report. I hope u can solve the issue and get back to me!

**Comment by tr7zw** [comment]
You have enhanced block entities installed and didn't which the notes said is incompatible right now. Turn off sign buffering in the settings.

**Comment by RazerLemon** [comment]
alr thanks
