### ISSUE TITLE
Servercore's BlockGetterMixin class has invalid @Redirect signature when paired with Exordium

### ISSUE THREAD

**Issue by owosoup** [tr7zw/Exordium#97]
**Bug**
Using Quilt loader, the mod crashes the game during mixins.

**Full crash log:**
pastebin.com/qfCYuCzz

**Reproduce**
Use the Quilt loader, Exordium and Servercore (modrinth.com/mod/servercore)

**Expected behavior:**
Minecraft starts and I enjoy my lag free world.

**Versions**
ServerCore: 1.3.5
Minecraft: 1.19.4
Exordium: 1.1.2

I have reported and closed the issue on servercore's github project, since the problem seems to be caused by Exordium.

![image](https://github.com/tr7zw/Exordium/assets/95828007/6a585c0e-026f-4050-adce-04b0ccc84c24)

**Comment by tr7zw** [comment]
For 1.19.4 use the older version where mixin extras is not inside, on 1.20 this should be fixed as part of #83.

**Comment by owosoup** [comment]
Alright, thanks!
